version: '3.7'

services:
  traefik:
    image: "traefik:v2.1.4"
    ports:
      - "80:80"           # api
      - "8080:8080"       # dashboard
      - "3000:3000"       # test-entry
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/traefik.yml:/etc/traefik/traefik.yml"
      - "./config/rules.yml:/config/rules.yml"

  test:
    image: zhenik/uuid:2.0
    container_name: test

  minio:
    image: minio/minio:RELEASE.2020-01-03T19-12-21Z
    container_name: minio
    ports:
      - "9876:9000" # for testing redirects
    environment:
      MINIO_ACCESS_KEY: "minio"
      MINIO_SECRET_KEY: "minio123"
    command: server /data