version: '3.7'

services:
  traefik:
    image: "traefik:v2.1.4"
    ports:
      - "80:80"           # api
      - "8080:8080"       # dashboard
      - "443:443"
      - "3000:3000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/traefik.yml:/etc/traefik/traefik.yml"
      - "./config/rules.yml:/config/rules.yml"

  test:
    image: zhenik/uuid:2.0
    container_name: test
#    ports:
#      - 3333:3000