version: '3.7'

services:
  traefik:
    image: traefik:v2.0
    ports:
      - "8000:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${PWD}/traefik.yml:/etc/traefik/traefik.yml"
      - "${PWD}/rules.yml:/etc/traefik/rules.yml"

  test:
    image: containous/whoami:v1.4.0
    container_name: test
    ports:
    - 11111:80