http:
  # Add the router
  routers:
    router0:
      entryPoints:
        - web
      service: service-foo
      rule: Path(`/foo`)
  # Add the service
  services:
    service-foo:
      loadBalancer:
        servers:
          - url: http://test/
          - url: http://test/
        passHostHeader: false