version: '3.7'

services:
  traefik:
    image: traefik:v2.0
    command:
      - --providers.docker
      - --providers.docker.usebindportip
      - --providers.docker.exposedbydefault=false
      - --log.level=INFO
      - --accesslog=true
      - --entryPoints.web.address=:80
      - --entryPoints.web.proxyProtocol.insecure
      - --entryPoints.websecure.address=:443
      - --entryPoints.websecure.proxyProtocol.insecure
      - --providers.file.directory=/etc/traefik
      - --providers.file.watch=true
      - --api.dashboard
      - --api
    environment:
#      TRAEFIK_PROVIDERS_FILE_WATCH: true
      TRAEFIK_PROVIDERS_FILE_DEBUGLOGGENERATEDTEMPLATE: "true"
#      TRAEFIK_PROVIDERS_FILE_DIRECTORY: "/etc/traefik/"
#      TRAEFIK_PROVIDERS_FILE_FILENAME: "/etc/traefik/traefik.yml"
#    command: -c /dev/null --web --docker --logLevel=DEBUG
#    networks:
#      - default
#      - project1
#      - project2
#      - project3
#    ports:
#      - '8000:80'
    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik:/etc/traefik"
#    labels:
#      - "traefik.backend=traefik"
#      - "traefik.port=8080"
#      - "traefik.frontend.rule=Host:traefik.docker.localhost"

  uuid1:
    image: zhenik/uuid:2.0
    ports:
    - 3000:3000

#  portainer:
#    image: portainer/portainer
#    restart: always
#    depends_on:
#      - traefik
#    command: --no-auth
#    networks:
#      - default
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    labels:
#      - 'traefik.backend=portainer'
#      - 'traefik.port=9000'
#      - 'traefik.frontend.rule=Host:portainer.docker.localhost'
#
#
#  adminer:
#    #    image: wodby/adminer:4.3-1.1.0
#    image: hardware/adminer
#    restart: always
#    depends_on:
#      - traefik
#    environment:
#      ADMINER_SALT: adminer-salt
#    networks:
#      - default
#      - project1
#      - project2
#      - project3
#    labels:
#      - "traefik.backend=adminer"
#      #      - "traefik.port=9000" # for wodby/adminer
#      - "traefik.port=8888" # for hardware/adminer
#      - "traefik.frontend.rule=Host:adminer.docker.localhost"
#
#
#
#networks:
#  default:
#    external:
#      name: prof_default
#  project1:
#    external:
#      name: learningwhy_default
#  project2:
#    external:
#      name: lotto_default
#  project3:
#    external:
#      name: cleand7_default