# WIP https://github.com/envoyproxy/envoy/tree/master/source/extensions/filters/network/zookeeper_proxy
version: "3"
services:
  proxy:
    image: envoyproxy/envoy:v1.13.0
    volumes:
    - "./envoy-kafka.yaml:/etc/envoy/envoy.yaml"
    expose:
      - "11111"
      - "9901"
    ports:
      - "11111:11111"
      - "9901:9901"
    depends_on:
      - zoo1
      - kafka1

  zoo1:
    image: confluentinc/cp-zookeeper:5.4.0
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: server.1=127.0.0.1:2888:3888

  kafka1:
    image: confluentinc/cp-kafka:5.4.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    volumes:
      - ./kafka1/data:/var/lib/kafka/data
    depends_on:
      - zoo1