http:
  routers:
    router1:
      rule: Host(`localhost`)
      service: service1
      entryPoints:
        - web
    router2:
      rule: Path(`/`)
      service: service2
#      middleware:
#        - remove-path
      entryPoints:
        - test-entry
  middlewares:
    remove-path:
      replacePath:
        path: "/"
  services:
    service1:
      loadBalancer:
        servers:
          - url: http://httpbin.org
    service2:
      loadBalancer:
        servers:
          - url: http://test:3000