global:
  sendAnonymousUsage: false

api:
  insecure: true
  dashboard: true
  debug: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  test-entry:
    address: ":3000"
providers:
#  docker:
#    exposedByDefault: false
  file:
    watch: true
    filename: /config/rules.yml
    debugLogGeneratedTemplate: true