# for debug nomad zoo&kafka deployment
# create proxy before run
# > consul connect proxy -service=proxy-to-kafka -upstream=kafka-bootstrap-server:9092 -log-level=TRACE
version: '3.7'
services:
  sr:
    image: confluentinc/cp-schema-registry:5.3.1
    network_mode: host
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: 0.0.0.0
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081 # default 8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://localhost:9092"