version: '3.7'

services:
  traefik:
    image: "traefik:v2.0.4"
    ports:
      - "80:80"
      - "443:443"
      - "8888:8888"
    labels:
      - "traefik.enable=true"
      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`traefik.docker.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/traefik.yml:/etc/traefik/traefik.yml"
      - "./config/rules.yml:/config/rules.yml"

  test:
    image: zhenik/uuid:2.0
