version: "3"
services:
  proxy:
    image: envoyproxy/envoy:v1.13.0
    volumes:
    - "./envoy.yaml:/etc/envoy/envoy.yaml"
    ports:
    - 1999:1999
    - 8001:8001

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
    expose:
      - "3306"
    ports:
      - "3306:3306"