http:
  routers:
    router-to-minio:
#      https://docs.traefik.io/routing/routers/#rule
#      based on reg expressions due to handle minio's redirects
      rule: "PathPrefix(`/minio/`, `/minio`)"
      service: "minio-service"
      entryPoints:
        - test-entry
  services:
    minio-service:
      loadBalancer:
#        passHostHeader: true
#        needs sticky cookie if more than one server behind loadBalancer
#        sticky:
#          cookie: {}
        servers:
          - url: http://minio:9000