http:
  routers:
    router1:
      rule: "Host(`localhost`)"
      service: service1
      entryPoints:
        - web
    router2:
      rule: "Path(`/t`)"
      service: service2
      middlewares:
        - "remove-path"
      entryPoints:
        - shara

#    router-to-minio1:
#      rule: "Path(`/`)"
#      service: "minio-service"
#      entryPoints:
#        - test-entry
    router-to-minio1:
      rule: "Path(`/minio-service`)"
      service: "minio-service"
      middlewares:
        - "remove-path"
      entryPoints:
        - test-entry
    router-to-minio2:
      rule: "PathPrefix(`/minio/`)"
      service: "minio-service"
      entryPoints:
        - test-entry

  middlewares:
    remove-path:
      replacePath:
        path: "/"
    minio-path:
      replacePath:
        path: "/minio"
  services:
    service1:
      loadBalancer:
        servers:
          - url: http://httpbin.org
    service2:
      loadBalancer:
        servers:
          - url: http://test:3000
    minio-service:
      loadBalancer:
        passHostHeader: true
#        sticky:
#          cookie: {}
        servers:
          - url: http://minio:9000